# Generated by Django 2.2 on 2020-02-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierater_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='titel',
            new_name='title',
        ),
    ]
